using System;
using System.Collections.Generic;

namespace TAC_AI.Templates
{
    public class BaseGamePopSpecials
    {
        public static HashSet<string> SelectedSpawns => new HashSet<string> {
            "attack crab",
"Albatross 1",
"Anchored Hover Three",
"Assault strike HC",
"attack cube",
"Baby Shark K61",
"battle hover",
"Better Future eCab",
"BF Speeder Bullet",
"Blue Dragon",
"Buff Bot",
"C50",
"Death Skimmer",
"Devil down",
"Dinkyprise",
"Drone 1",
"Drone 83721",
"Drone F7",
"ESS_SABER",
"Flugscheibe Mk X",
"Flying Beyblade",
"Generic Vehicle #6",
"Grace Dinger",
"Grundigger",
"Guardian 78792",
"Guardian BFV",
"H1",
"H375",
"Hover Buddy 7729",
"Hover Buddy 8237",
"Hover Buddy 873291",
"Hover Buddy MK2",
"hover harvester ",
"HoverBird Mk6e",
"Hoverbird Mk7c",
"hovercraft 892",
"Hovercraft 9810",
"Hovercraft BetterFut",
"HoverPlane",
"Hybrid VHB_H Racer 1",
"Interceptor KV2",
"Junction Drift",
"Larger UFO",
"laser time ",
"Light Flight Delight",
"Luracasmus Hover",
"Manta Rey 8930123",
"Mega Racer",
"MenuBrawl Floater v1",
"Moonbeam Hovercycle 892",
"Nephele 100i",
"Nimble shots",
"No1",
"No13190",
"Peeper",
"Pet_T Puppy",
"Scarab",
"Scorpion Dark",
"Sentinel X45",
"sharkS2",
"Spear 813",
"SPear",
"Squidlet",
"Sting Ray Sting Ray",
"Tommahawk",
"Twiddle Skipper",
"Velocity 813",
"Vespr Sting",
"Wind Whisper",
        };
    }
}
