namespace TAC_AI.Templates
{
    public enum SpawnBaseTypes
    {
        NotAvail,

        GSO0Base,
        GCTotum,
        VENPipperoni,
        HERelay,
        BFCyberFlote,
        RRSideswipe,

        GSOSeller,
        GSOMidBase,
        GSOMinerCluster,
        GSOAIMinerProduction,
        GSOTechFactory,
        GSOHVYTankFactory,
        GSOAirbase,
        GSOStarport,
        GSOCorvetteGantry,
        GSOMacrocosmGantry,
        GSOMilitaryBase,

        GCMiningRig,
        GCTerraBore,
        GCLoaderLauncher,
        GCProspectorHub,
        GCMiningLaser,
        GCDefTurret,
        GCHeadquarters,

        VENTuningShop,
        VENGasStation,
        VENPitStop,
        VENRallyHost,
        VENAviationCenter,
        VENGasSilo,
        VENSpeedac,

        HECombatStation,
        HEOilDerrick,
        HEComsat,
        HEMunitionsDepot,
        HETankFactory,
        HEAAFactory,
        HEArtyFactory,
        HEXLTankFactory,
        HEAircraftGarrison,
        HEXLAircraftGarrison,
        HECommandCentre,

        BFGains,
        BFExtractor,
        BFDrifter,
        BFShampoo,
        BFHoverFactory,
        BFSporkFabricator,
        BFNoleusAutoworks,

        RRDecanter,
        RRSampler,
        RRFactory,
        RRHeavyFactory,
        RRScienceVessel,

        GSOLightDefense,
        GSOTowerDefense,
        GSOMegaDefense,
        GCMiningLaserLite,
        GCDefenseTurret,
        VENDeputyTurret,
        HEPerimeterDefense,
        HECapitalDefense,
        BFOrbitarGuard,

        GSOTonyTeam,
        GSOHarvesterTech,
        GCHarvesterTech,
        HEHarvesterTech,
        BFHarvesterTech,
        RRHarvesterTech,

        AttractServo,
        TACInvaderAttract,
        TACInvaderAttract2,
        TACOutpostMissions,
        TACSentinelTurret,

        GSOLiftOff,
        GSOEpicTony,
        GSOAirdropSquad,
        GSOHammer,
        GSOFightOrFlight,

        GCFuryFlier,

        VENLiftOff,
        VENPuffPlane,
        VENDraftPlane,
        VENZephrPlane,
        VENTornadoPlane,
        VENHotWings,
        VENMachinator,

        HEPeanutJet,
        HEProx,
        HEVengence,
        HEDropship,
        HEBombsAway,
        HECyclone,

        BFEchoAir,
        BFColossus,
        BFFrizbee,
        BFOblivion,

        RRDragonFlop,

        SJBayonase,

        GSOQuadGale,
        GSOQuadGaleM,

        GCDigginFlyDual,
        GCDiggersBee,
        GCHelicross,
        GCMadMiner,

        HESheertail,
        HEPocketApache,
        HESmashApache,
        BFeClipse,

        SJWindbag,

        GSOShallowWaterGuard,
        GCPlasmaDredge,
        GCYukonCharleyDredge,
        VENScurry,
        VENNautilus,
        HESwaddleBoat,
        HEDreadnaught,
        HEBattleSwivels,
        BFLuxYacht,

        FTUEGSOGrade1Bote,
        FTUEGSOGrade2Bote,
        FTUEGSOGrade3Bote,
        FTUEGSOGrade4Bote,
        FTUEGSOGrade5Bote,
        FTUEGSOGrade1BoteFallBack,
        FTUEGSOGrade2BoteFallBack,
        FTUEGSOGrade3BoteFallBack,
        FTUEGSOGrade4BoteFallBack,
        FTUEGSOGrade5BoteFallBack,

        GSOSpaceshipMini,
        GSOSpaceshipCompact,
        GSOSpaceship,
        HEClatoe,
        HECroc,
        BFTrident,

        GSOSpaceArty,
        VENSpaceArty,
        HESpaceArty,
        BFSpaceArty,

        VENHarvester,
        Chungmus,
        TidusJ,
        U1T1M4T3P4RTYBUSSS,
        Kickball2,

        AntiBomb,
        AntiSkyScience,

        Midge,
        Damselfly,

        Vette2,

        Invulnerable2,
        Tyrant2,

        GSO0GExtractor,
        GSOPowerStation,
        GSOQuickBuck,

        TINYTANKS,
        LDAInitiator,
        VertuDefartillery,
        Vertusolarnode,
        AntishieldtinyTank,
        antiprotons,
        TestlaLazeRR,
        ThermalRRat,
        V_LDAdrone,
        Armageddon,
        VertuLEAD,
        DefLRMSentry,
        LDADefBattleTower,
        PetesSecretStash,
        VertuDeffort,
        TestSubjectACDC73,
        Beta,
        Cosmic,
        Electron,
        ExpRamp,
        ExplodeTheory,
        EXPloder,
        LABRover,
        Meteorminer,
        Meterordriller,
        PlasmaTester,
        PlasmaTheory,
        Proton,
        RampTank,
        ResearchRamp,
        RocketCroc,
        ScienceExplorer,
        ScrapSpider,
        ShotDog,
        SoundRover,
        SoundScience,
        SpaceMiner,
        TESTGravity,
        TESTPlasma,
        TESTSound,
        TeslaHolder,
        Thebattleprototype,
        TheCrabparatus,
        TherocketBEE,
        ZAPPer,
        EXPHover,
        QueenBee,
        ThebRRokenHover,
        Vertupyrotech,
        VertuDefnode,
        ScienceTrack,
        VertuAIscout,
        Vertubiotech,
        Antimatter,
        Antimattercarrier,
        LDALaserdrone,
        Defbattletower,
        Defdisruptersentry,
        DefHeavyLaserSentry,
        DefSentryGun,
        DefSentryGunB,
        LDAcannontower,
        LDALightLaserHtank,
        MiniPebbles,
        Monolith,
        V_LDADefHMT,
        VertuBattleDrone,
        Vertucapitaltech,
        VertuDEFcannon,
        VertuENCV2,
        Vertumobilebastion,
        BigShotR,
        Geckette,
        LDABrawlerTank,
        LDAKothTankV2,
        LDAMissiledrone,
        LDATank,
        SY7_Staffer,
        V_LDAAITank,
        V_LDAbasiancedtank,
        V_LDAcommandtank,
        V_LDADroneTank,
        V_LDALightTank,
        V_LDAScouttank,
        Vertuangrytech,
        VertuAssaulttank,
        VertuenforcerMk2,
        VertuTerrorTech,
        Worker,
        Bunker,
        V_LDAbattletank,
        VertuassaultT1,
        Vertubehemothtank,
        VertuhardytankV2,
        Vertupaintrain,
        Vertureactortank,
        Vertusaigetech,
        Vertustormtank,
        VertuTitan,
        Vertusdoomtrain,
        Maikro,
        Scythe,
        Dinghy,
        Intrepid,
        LDAMicroBattleship,
        Piranha,
        Spyder,
        VertuexperimentalO,
        Vertulasercrusier,
        Brawler,
        DCZ5ScorpionMK2R,
        MaulV4,
        Stingray,
        TX98ShockwaveMk2R,
        V_LDAACSBSToaster,
        V_LDABattleCruiser,
        V_LDABattletech,
        V_LDABSIronWill,
        V_LDAEscortcruiser,
        V_LDAHeavycruiser,
        V_LDAHeavyTank,
        V_LDATeslatank,
        V_LDRhovertank,
        VertuAtmoBattleship,
        VertuLaserBattleship,
        Hatchet,
        V_LDADefPWatcher,
        VertuDefPOverwatch,
        VertumissileDEFP,
        MecanumSpider,
        Prototypedrone,
        Crescent,
        V_LDAResponcedrone,
        DiolysisC6WyvernR,
        Hornet,
        Hummingbird,
        StarN422281337,
        PreludeMP,
        V_LDAAssaultdrone,

    }

}
